server:
  port: 8080

app:
  dev-model: false

  uac:
    target: server:view
    keyName: token-s
    expire: 30
    serverUrl: http://uac.asoco.com.cn
    authUrl: https://nav.asoco.com.cn?backType=web&backUrl=

  outside:
    apiUrl: https://api.asoco.com.cn
    accessToken: 9340eb2a391144e1aac14c6b6d53
    dseUrl: http://192.168.1.177:8090/api/dse
    videoUrl: /api/oss/videos
    videoListUrl: /api/oss/hik/video
    videoListByRoleUrl: /api/oss/video
    uploadUrl: /oss/upload
    uploadB64Url: /oss/upload-b64
    bucketName: mybatis-server

#日志配置
logging:
  #在项目的根目录下添加server.log文件，打印系统启动、异常等日志
  path:  ../../mybatis-server/
  file: server.log


spring:

  #swagger等配置
  profiles:
    #配置当前的环境：开发环境还是生产环境dev、prod
    active: dev

  #数据源配置
  datasource:
    #name: test
    url: jdbc:mysql://127.0.0.1:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root2
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #type: com.zaxxer.hikari.HikariDataSource
    #driver-class-name: com.mysql.cj.jdbc.Driver   数据源的配置好好总结一下
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  #发送右键配置
  mail:
    host: smtp.163.com #发送邮件服务器
    username: ...@163.com #发送邮件的邮箱地址
    password: ... #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties.mail.smtp.port: 994 #465或者994
    from: ...@163.com # 发送邮件的地址，和上面username一致可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

  #热部署配置
  devtools:
    remote:
      restart:
        enabled: true
    restart:
      additional-paths: springboot-mybatis-server/src/main


## MyBatis相关配置
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.q8888.springboot.mybatis.server.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



